### ISSUE TITLE
Docker run failed with exit code 2

### ISSUE THREAD

**Issue by shireenrao** [jefftriplett/python-actions#6]
I am very new to github actions and tried it out for the first time today. When I tried to use python-actions, I see this failure:

https://github.com/shireenrao/abc/commit/3bd0c8896d680a4fcfca4b20cc7461cc489f89ee/checks?check_suite_id=250305286#step:4:3

Here is my main.yml
```
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: jefftriplett/python-actions@master
    - name: Install dependencies
      run: pip install --upgrade pip && pip install -r requirements.txt
    - name: Deploy
      run: ./deploy-to-gh-pages.sh
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_KEY }}

```
Would you have any thoughts on why this failed?
